In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd

df = pd.DataFrame([
    (1, '北海道', 69, ['青森']),
    (2, '青森', 136, ['北海道', '岩手', '秋田']),
    (3, '岩手', 84, ['青森', '宮城', '秋田']),
    (4, '宮城', 321, ['岩手', '秋田', '山形', '福島']),
    (5, '秋田', 88, ['青森', '岩手', '宮城', '山形']),
    (6, '山形', 121, ['宮城', '秋田', '福島', '新潟']),
    (7, '福島', 139, ['宮城', '山形', '茨城', '栃木', '群馬', '新潟']),
    (8, '茨城', 478, ['福島', '栃木', '埼玉', '千葉']),
    (9, '栃木', 308, ['福島', '茨城', '群馬', '埼玉']),
    (10, '群馬', 310, ['福島', '栃木', '埼玉', '新潟', '長野']),
    (11, '埼玉', 1913, ['茨城', '栃木', '群馬', '千葉', '東京', '山梨', '長野']),
    (12, '千葉', 1207, ['茨城', '埼玉', '東京']),
    (13, '東京', 6169, ['埼玉', '千葉', '神奈川', '山梨']),
    (14, '神奈川', 3778, ['東京', '山梨', '静岡']),
    (15, '新潟', 183, ['山形', '福島', '群馬', '富山', '長野']),
    (16, '富山', 251, ['新潟', '石川', '長野', '岐阜']),
    (17, '石川', 276, ['富山', '福井', '岐阜']),
    (18, '福井', 188, ['石川', '岐阜', '滋賀', '京都']),
    (19, '山梨', 187, ['埼玉', '東京', '神奈川', '長野', '静岡']),
    (20, '長野', 155, ['群馬', '埼玉', '新潟', '富山', '山梨', '岐阜', '静岡', '愛知']),
    (21, '岐阜', 191, ['富山', '石川', '福井', '長野', '愛知', '三重', '滋賀']),
    (22, '静岡', 476, ['神奈川', '山梨', '長野', '愛知']),
    (23, '愛知', 1447, ['長野', '岐阜', '静岡', '三重']),
    (24, '三重', 315, ['岐阜', '愛知', '滋賀', '京都', '奈良', '和歌山']),
    (25, '滋賀', 352, ['福井', '岐阜', '三重', '京都']),
    (26, '京都', 566, ['福井', '三重', '滋賀', '大阪', '兵庫', '奈良']),
    (27, '大阪', 4640, ['京都', '兵庫', '奈良', '和歌山']),
    (28, '兵庫', 659, ['京都', '大阪', '鳥取', '岡山', '徳島']),
    (29, '奈良', 370, ['三重', '京都', '大阪', '和歌山']),
    (30, '和歌山', 204, ['三重', '大阪', '奈良']),
    (31, '鳥取', 164, ['兵庫', '島根', '岡山', '広島']),
    (32, '島根', 104, ['鳥取', '広島', '山口']),
    (33, '岡山', 270, ['兵庫', '鳥取', '広島', '香川']),
    (34, '広島', 335, ['鳥取', '島根', '岡山', '山口', '愛媛']),
    (35, '山口', 230, ['島根', '広島', '福岡']),
    (36, '徳島', 182, ['兵庫', '香川', '愛媛', '高知']),
    (37, '香川', 520, ['岡山', '徳島', '愛媛']),
    (38, '愛媛', 244, ['広島', '徳島', '香川', '高知']),
    (39, '高知', 103, ['徳島', '愛媛']),
    (40, '福岡', 1023, ['山口', '佐賀', '熊本', '大分']),
    (41, '佐賀', 341, ['福岡', '長崎']),
    (42, '長崎', 333, ['佐賀']),
    (43, '熊本', 241, ['福岡', '大分', '宮崎', '鹿児島']),
    (44, '大分', 184, ['福岡', '熊本', '宮崎']),
    (45, '宮崎', 143, ['熊本', '大分', '鹿児島']),
    (46, '鹿児島', 179, ['熊本', '宮崎', '沖縄']),
    (47, '沖縄', 628, ['鹿児島']),
], columns=['id', 'name', 'density (ppl/km2)', 'adjacent'])
df['adjacent_id'] = df['adjacent'].map(lambda names: [df[df['name'] == name].iloc[0]['id'] for name in names])
df

,id,name,density (ppl/km2),adjacent,adjacent_id
0,1,北海道,69,[青森],[2]
1,2,青森,136,"[北海道, 岩手, 秋田]","[1, 3, 5]"
2,3,岩手,84,"[青森, 宮城, 秋田]","[2, 4, 5]"
3,4,宮城,321,"[岩手, 秋田, 山形, 福島]","[3, 5, 6, 7]"
4,5,秋田,88,"[青森, 岩手, 宮城, 山形]","[2, 3, 4, 6]"
5,6,山形,121,"[宮城, 秋田, 福島, 新潟]","[4, 5, 7, 15]"
6,7,福島,139,"[宮城, 山形, 茨城, 栃木, 群馬, 新潟]","[4, 6, 8, 9, 10, 15]"
7,8,茨城,478,"[福島, 栃木, 埼玉, 千葉]","[7, 9, 11, 12]"
8,9,栃木,308,"[福島, 茨城, 群馬, 埼玉]","[7, 8, 10, 11]"
9,10,群馬,310,"[福島, 栃木, 埼玉, 新潟, 長野]","[7, 9, 11, 15, 20]"
10,11,埼玉,1913,"[茨城, 栃木, 群馬, 千葉, 東京, 山梨, 長野]","[8, 9, 10, 12, 13, 19, 20]"
11,12,千葉,1207,"[茨城, 埼玉, 東京]","[8, 11, 13]"
12,13,東京,6169,"[埼玉, 千葉, 神奈川, 山梨]","[11, 12, 14, 19]"
13,14,神奈川,3778,"[東京, 山梨, 静岡]","[13, 19, 22]"
14,15,新潟,183,"[山形, 福島, 群馬, 富山, 長野]","[6, 7, 10, 16, 20]"
15,16,富山,251,"[新潟, 石川, 長野, 岐阜]","[15, 17, 20, 21]"
16,17,石川,276,"[富山, 福井, 岐阜]","[16, 18, 21]"
17,18,福井,188,"[石川, 岐阜, 滋賀, 京都]","[17, 21, 25, 26]"
18,19,山梨,187,"[埼玉, 東京, 神奈川, 長野, 静岡]","[11, 13, 14, 20, 22]"
19,20,長野,155,"[群馬, 埼玉, 新潟, 富山, 山梨, 岐阜, 静岡, 愛知]","[10, 11, 15, 16, 19, 21, 22, 23]"
20,21,岐阜,191,"[富山, 石川, 福井, 長野, 愛知, 三重, 滋賀]","[16, 17, 18, 20, 23, 24, 25]"
21,22,静岡,476,"[神奈川, 山梨, 長野, 愛知]","[14, 19, 20, 23]"
22,23,愛知,1447,"[長野, 岐阜, 静岡, 三重]","[20, 21, 22, 24]"
23,24,三重,315,"[岐阜, 愛知, 滋賀, 京都, 奈良, 和歌山]","[21, 23, 25, 26, 29, 30]"
24,25,滋賀,352,"[福井, 岐阜, 三重, 京都]","[18, 21, 24, 26]"
25,26,京都,566,"[福井, 三重, 滋賀, 大阪, 兵庫, 奈良]","[18, 24, 25, 27, 28, 29]"
26,27,大阪,4640,"[京都, 兵庫, 奈良, 和歌山]","[26, 28, 29, 30]"
27,28,兵庫,659,"[京都, 大阪, 鳥取, 岡山, 徳島]","[26, 27, 31, 33, 36]"
28,29,奈良,370,"[三重, 京都, 大阪, 和歌山]","[24, 26, 27, 30]"
29,30,和歌山,204,"[三重, 大阪, 奈良]","[24, 27, 29]"
30,31,鳥取,164,"[兵庫, 島根, 岡山, 広島]","[28, 32, 33, 34]"
31,32,島根,104,"[鳥取, 広島, 山口]","[31, 34, 35]"
32,33,岡山,270,"[兵庫, 鳥取, 広島, 香川]","[28, 31, 34, 37]"
33,34,広島,335,"[鳥取, 島根, 岡山, 山口, 愛媛]","[31, 32, 33, 35, 38]"
34,35,山口,230,"[島根, 広島, 福岡]","[32, 34, 40]"
35,36,徳島,182,"[兵庫, 香川, 愛媛, 高知]","[28, 37, 38, 39]"
36,37,香川,520,"[岡山, 徳島, 愛媛]","[33, 36, 38]"
37,38,愛媛,244,"[広島, 徳島, 香川, 高知]","[34, 36, 37, 39]"
38,39,高知,103,"[徳島, 愛媛]","[36, 38]"
39,40,福岡,1023,"[山口, 佐賀, 熊本, 大分]","[35, 41, 43, 44]"
40,41,佐賀,341,"[福岡, 長崎]","[40, 42]"
41,42,長崎,333,[佐賀],[41]
42,43,熊本,241,"[福岡, 大分, 宮崎, 鹿児島]","[40, 44, 45, 46]"
43,44,大分,184,"[福岡, 熊本, 宮崎]","[40, 43, 45]"
44,45,宮崎,143,"[熊本, 大分, 鹿児島]","[43, 44, 46]"
45,46,鹿児島,179,"[熊本, 宮崎, 沖縄]","[43, 45, 47]"
46,47,沖縄,628,[鹿児島],[46]

In [2]:
data = df['density (ppl/km2)'].to_numpy()
adjacency = np.zeros((len(df),)*2, dtype='int8')
for _, row in df.iterrows():
    i_plus_one = row['id']
    for j_plus_one in row['adjacent_id']:
        adjacency[i_plus_one-1, j_plus_one-1] = 1

In [13]:
from echelon.api import EchelonAnalysis
analyzer = EchelonAnalysis()
result = analyzer(data, adjacency)
result

Result_EchelonAnalysis(peak_echelons=[[12, 13, 10, 11, 7], [26, 27, 25, 28, 24], [22], [39, 40, 41, 42], [46], [36], [33], [3], [16, 15], [1]], foundation_echelons=[[21], [23, 9, 8], [32, 33, 37], [34, 29], [20, 17, 18, 43, 14, 35], [45, 30, 19, 44], [6, 5, 31, 38], [4, 3, 2, 0]], oracle=<echelon.oracle.NdarrayEchelonOracle object at 0x7f9040768208>)

In [14]:
sorted(sum(result.peak_echelons, []) + sum(result.foundation_echelons, []))

[0,
 1,
 2,
 3,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46]

In [16]:
analyzer.cluster(result).table

  representatives                                            indices
0            [12]  [12, 13, 10, 11, 7, 21, 9, 8, 18, 14, 19, 6, 5...
1            [26]  [26, 27, 25, 28, 24, 23, 32, 33, 37, 34, 29, 2...
2            [22]  [22, 21, 23, 29, 20, 17, 18, 19, 21, 23, 9, 8,...
3            [39]  [39, 40, 41, 42, 34, 43, 45, 44, 31, 33, 37, 3...
4            [46]                           [46, 45, 44, 43, 45, 44]
5            [36]  [36, 32, 33, 37, 34, 35, 30, 31, 38, 32, 33, 3...
6    [33, 33, 33]  [33, 32, 33, 37, 34, 35, 30, 31, 38, 32, 33, 3...
7       [3, 3, 3]    [3, 6, 5, 4, 3, 2, 9, 8, 14, 19, 6, 5, 4, 3, 2]
8            [21]  [16, 15, 20, 17, 14, 19, 6, 5, 4, 3, 2, 21, 23...
9          [3, 3]                  [1, 4, 3, 2, 0, 6, 5, 4, 3, 2, 0]